apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- schemas

patches:
- path: patches/io.openshift.config.v1.OAuth.yaml
- path: patches/io.openshift.multicluster.v1.MultiClusterEngine.yaml
